import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { format } from "date-fns";
import {
  Cloud, TrendingUp, TrendingDown, Minus, Sparkles, Users, GraduationCap,
  ListChecks, CalendarClock, Brain, Loader2,
} from "lucide-react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { getDayBriefing, type DayBriefing } from "@/lib/day-briefing.functions";
import { cn } from "@/lib/utils";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  date: Date | null;
};

export function DayDetailDialog({ open, onOpenChange, date }: Props) {
  const fetchBriefing = useServerFn(getDayBriefing);
  const iso = date ? format(date, "yyyy-MM-dd") : null;

  const { data, isLoading, error } = useQuery({
    queryKey: ["day-briefing", iso],
    queryFn: () => fetchBriefing({ data: { date: iso! } }),
    enabled: open && !!iso,
    staleTime: 5 * 60 * 1000,
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl">
            {date ? format(date, "EEEE, d MMMM yyyy") : "Day briefing"}
          </DialogTitle>
          <DialogDescription>
            Weather, markets, horoscope, roster, tasks and meetings — generated by AI.
          </DialogDescription>
        </DialogHeader>

        {isLoading && (
          <div className="flex items-center gap-2 py-12 justify-center text-muted-foreground">
            <Loader2 className="h-5 w-5 animate-spin" />
            <span>Building your daily briefing…</span>
          </div>
        )}

        {error && (
          <div className="rounded-lg border border-destructive/40 bg-destructive/5 p-4 text-sm text-destructive">
            Failed to load briefing: {(error as Error).message}
          </div>
        )}

        {data && <BriefingBody data={data} />}
      </DialogContent>
    </Dialog>
  );
}

function Section({ icon: Icon, title, children }: { icon: React.ElementType; title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-xl border bg-card p-4 shadow-sm">
      <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
        <Icon className="h-4 w-4" />
        {title}
      </h3>
      <div className="space-y-2 text-sm">{children}</div>
    </section>
  );
}

function BriefingBody({ data }: { data: DayBriefing }) {
  return (
    <div className="grid gap-3 md:grid-cols-2">
      <Section icon={Brain} title="AI summary">
        <p className="leading-relaxed">{data.ai_summary}</p>
      </Section>

      <Section icon={Cloud} title={`Weather — ${data.weather.location}`}>
        <p className="font-medium">{data.weather.summary}</p>
        <div className="flex flex-wrap gap-3 text-xs text-muted-foreground">
          {data.weather.high_c != null && <span>High {data.weather.high_c}°C</span>}
          {data.weather.low_c != null && <span>Low {data.weather.low_c}°C</span>}
          <span>{data.weather.precipitation}</span>
          <span>{data.weather.wind}</span>
        </div>
      </Section>

      <Section icon={TrendingUp} title="Markets">
        {data.markets.length === 0 && <p className="text-muted-foreground">No market data.</p>}
        {data.markets.map((m) => {
          const Icon = m.direction === "up" ? TrendingUp : m.direction === "down" ? TrendingDown : Minus;
          const color = m.direction === "up" ? "text-emerald-600" : m.direction === "down" ? "text-rose-600" : "text-muted-foreground";
          return (
            <div key={m.symbol} className="flex items-start justify-between gap-2 border-b last:border-0 pb-2 last:pb-0">
              <div className="min-w-0">
                <div className="font-medium">{m.name} <span className="text-xs text-muted-foreground">({m.symbol})</span></div>
                <div className="text-xs text-muted-foreground line-clamp-2">{m.note}</div>
              </div>
              <div className={cn("text-right tabular-nums whitespace-nowrap", color)}>
                <div className="font-semibold">{m.price}</div>
                <div className="flex items-center justify-end gap-1 text-xs">
                  <Icon className="h-3 w-3" />
                  {m.change_pct}
                </div>
              </div>
            </div>
          );
        })}
      </Section>

      <Section icon={Sparkles} title="Horoscope">
        <div>
          <Badge variant="outline" className="mb-1">Sagittarius</Badge>
          <p className="text-muted-foreground">{data.horoscope.sagittarius}</p>
        </div>
        <div className="pt-2 border-t">
          <Badge variant="outline" className="mb-1">Rat (Chinese)</Badge>
          <p className="text-muted-foreground">{data.horoscope.chinese_rat}</p>
        </div>
      </Section>

      <Section icon={Users} title={`Roster (${data.roster.length})`}>
        {data.roster.length === 0 && <p className="text-muted-foreground">No one rostered.</p>}
        {data.roster.map((r, i) => (
          <div key={i} className="flex items-center justify-between">
            <span className="font-medium">{r.name}</span>
            <span className="text-xs text-muted-foreground">
              {r.is_off ? "OFF" : `${r.start ?? "—"}–${r.end ?? "—"}`} · {r.roster_type}
            </span>
          </div>
        ))}
      </Section>

      <Section icon={GraduationCap} title={`Training (${data.training.length})`}>
        {data.training.length === 0 && <p className="text-muted-foreground">No training scheduled.</p>}
        {data.training.map((t, i) => (
          <div key={i} className="border-b last:border-0 pb-2 last:pb-0">
            <div className="flex items-center justify-between">
              <span className="font-medium">{t.name}</span>
              <span className="text-xs text-muted-foreground">{t.start ?? "—"}–{t.end ?? "—"}</span>
            </div>
            {t.training_text && <p className="text-xs text-muted-foreground">{t.training_text}</p>}
          </div>
        ))}
      </Section>

      <Section icon={ListChecks} title={`Tasks (${data.tasks.length})`}>
        {data.tasks.length === 0 && <p className="text-muted-foreground">No open tasks.</p>}
        {data.tasks.map((t) => (
          <div key={t.id} className="flex items-start gap-2">
            <Badge
              variant={t.priority === 1 ? "destructive" : t.priority === 2 ? "default" : "secondary"}
              className="shrink-0"
            >
              P{t.priority ?? "?"}
            </Badge>
            <span className="flex-1">{t.content}</span>
          </div>
        ))}
      </Section>

      <Section icon={CalendarClock} title={`Meetings (${data.meetings.length})`}>
        {data.meetings.length === 0 && <p className="text-muted-foreground">No meetings.</p>}
        {data.meetings.map((m) => (
          <div key={m.id} className="border-b last:border-0 pb-2 last:pb-0">
            <div className="flex items-center justify-between">
              <span className="font-medium">{m.title}</span>
              <span className="text-xs tabular-nums text-orange-accent">
                {format(new Date(m.datetime), "HH:mm")}
              </span>
            </div>
            {m.location && <p className="text-xs text-muted-foreground">@ {m.location}</p>}
            {m.notes && <p className="text-xs text-muted-foreground line-clamp-2">{m.notes}</p>}
          </div>
        ))}
      </Section>
    </div>
  );
}
