/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRosterRouteImport } from './routes/training-roster'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksP1TaskNotifierRouteImport } from './routes/api/public/hooks/p1-task-notifier'

const TrainingRosterRoute = TrainingRosterRouteImport.update({
  id: '/training-roster',
  path: '/training-roster',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksP1TaskNotifierRoute =
  ApiPublicHooksP1TaskNotifierRouteImport.update({
    id: '/api/public/hooks/p1-task-notifier',
    path: '/api/public/hooks/p1-task-notifier',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/diary': typeof DiaryRoute
  '/email': typeof EmailRoute
  '/ideas': typeof IdeasRoute
  '/images': typeof ImagesRoute
  '/itinerary': typeof ItineraryRoute
  '/login': typeof LoginRoute
  '/medical': typeof MedicalRoute
  '/meetings': typeof MeetingsRoute
  '/roster': typeof RosterRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/training-roster': typeof TrainingRosterRoute
  '/api/public/hooks/p1-task-notifier': typeof ApiPublicHooksP1TaskNotifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/diary': typeof DiaryRoute
  '/email': typeof EmailRoute
  '/ideas': typeof IdeasRoute
  '/images': typeof ImagesRoute
  '/itinerary': typeof ItineraryRoute
  '/login': typeof LoginRoute
  '/medical': typeof MedicalRoute
  '/meetings': typeof MeetingsRoute
  '/roster': typeof RosterRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/training-roster': typeof TrainingRosterRoute
  '/api/public/hooks/p1-task-notifier': typeof ApiPublicHooksP1TaskNotifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/diary': typeof DiaryRoute
  '/email': typeof EmailRoute
  '/ideas': typeof IdeasRoute
  '/images': typeof ImagesRoute
  '/itinerary': typeof ItineraryRoute
  '/login': typeof LoginRoute
  '/medical': typeof MedicalRoute
  '/meetings': typeof MeetingsRoute
  '/roster': typeof RosterRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/training-roster': typeof TrainingRosterRoute
  '/api/public/hooks/p1-task-notifier': typeof ApiPublicHooksP1TaskNotifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/diary'
    | '/email'
    | '/ideas'
    | '/images'
    | '/itinerary'
    | '/login'
    | '/medical'
    | '/meetings'
    | '/roster'
    | '/schedules'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/training-roster'
    | '/api/public/hooks/p1-task-notifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/diary'
    | '/email'
    | '/ideas'
    | '/images'
    | '/itinerary'
    | '/login'
    | '/medical'
    | '/meetings'
    | '/roster'
    | '/schedules'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/training-roster'
    | '/api/public/hooks/p1-task-notifier'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/diary'
    | '/email'
    | '/ideas'
    | '/images'
    | '/itinerary'
    | '/login'
    | '/medical'
    | '/meetings'
    | '/roster'
    | '/schedules'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/training-roster'
    | '/api/public/hooks/p1-task-notifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  DiaryRoute: typeof DiaryRoute
  EmailRoute: typeof EmailRoute
  IdeasRoute: typeof IdeasRoute
  ImagesRoute: typeof ImagesRoute
  ItineraryRoute: typeof ItineraryRoute
  LoginRoute: typeof LoginRoute
  MedicalRoute: typeof MedicalRoute
  MeetingsRoute: typeof MeetingsRoute
  RosterRoute: typeof RosterRoute
  SchedulesRoute: typeof SchedulesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRoute
  TrainingRosterRoute: typeof TrainingRosterRoute
  ApiPublicHooksP1TaskNotifierRoute: typeof ApiPublicHooksP1TaskNotifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-roster': {
      id: '/training-roster'
      path: '/training-roster'
      fullPath: '/training-roster'
      preLoaderRoute: typeof TrainingRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/p1-task-notifier': {
      id: '/api/public/hooks/p1-task-notifier'
      path: '/api/public/hooks/p1-task-notifier'
      fullPath: '/api/public/hooks/p1-task-notifier'
      preLoaderRoute: typeof ApiPublicHooksP1TaskNotifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  DiaryRoute: DiaryRoute,
  EmailRoute: EmailRoute,
  IdeasRoute: IdeasRoute,
  ImagesRoute: ImagesRoute,
  ItineraryRoute: ItineraryRoute,
  LoginRoute: LoginRoute,
  MedicalRoute: MedicalRoute,
  MeetingsRoute: MeetingsRoute,
  RosterRoute: RosterRoute,
  SchedulesRoute: SchedulesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  TrainingRosterRoute: TrainingRosterRoute,
  ApiPublicHooksP1TaskNotifierRoute: ApiPublicHooksP1TaskNotifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
